# Generated by Django 3.0.8 on 2020-09-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TMB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], max_length=1)),
            ],
        ),
    ]
