# Generated by Django 3.0.8 on 2020-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmb',
            name='idade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
