# Generated by Django 3.0.8 on 2020-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0002_tmb_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmb',
            name='atividade',
            field=models.CharField(choices=[('1', 'Sedentário(pouco ou nenhum exercício)'), ('2', 'Levemente Ativo(exercícios leves ou pratica 1-3 dias / semana)'), ('3', 'Moderadamente Ativo(exercícios moderados de 3-5 dias / semana)'), ('4', 'Muito Ativo(exercício intenso de 6 a 7 dias / semana)'), ('5', 'Super Ativo(exercício muito pesado e trabalho labor físico / braçal)')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmb',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
