# Generated by Django 3.0.8 on 2020-09-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_auto_20200906_1632'),
        ('tmb', '0003_auto_20200906_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmb',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.Atividade'),
        ),
    ]
