# Generated by Django 3.0.8 on 2020-09-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0004_auto_20200906_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmb',
            name='total',
            field=models.IntegerField(),
        ),
    ]
