# Generated by Django 3.0.8 on 2020-09-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0007_auto_20200906_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmb',
            name='classificacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmb',
            name='imc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmb',
            name='peso_ideal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
