# Generated by Django 3.0.8 on 2020-09-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0008_auto_20200906_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmb',
            name='peso_ideal',
        ),
    ]
