# Generated by Django 3.0.8 on 2020-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
