# Generated by Django 3.0.7 on 2020-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentostacoaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('alimentos', models.ManyToManyField(to='alimentostacoaz.Alimento')),
            ],
            options={
                'db_table': 'dieta',
            },
        ),
    ]
