# Generated by Django 3.0.7 on 2020-06-30 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alimentostacoaz', '0001_initial'),
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieta',
            name='alimentos',
            field=models.ManyToManyField(blank=True, null=True, to='alimentostacoaz.Alimento'),
        ),
        migrations.AlterField(
            model_name='dieta',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
