# Generated by Django 3.0.7 on 2020-07-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0002_auto_20200630_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='observacao',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
