# Generated by Django 3.0.7 on 2020-07-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentostacoaz', '0001_initial'),
        ('dietas', '0003_dieta_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='alimentos',
            field=models.ManyToManyField(blank=True, to='alimentostacoaz.Alimento'),
        ),
    ]
