# Generated by Django 3.0.8 on 2020-09-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmb', '0001_initial'),
        ('dietas', '0003_dieta_recomendacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='TMB',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tmb.TMB'),
            preserve_default=False,
        ),
    ]
