# Generated by Django 3.0.8 on 2020-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='corretor',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
