from django.db import models


# Create your models here.
class Nutriente(models.Model):
    alanine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    arginine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    ashes_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    aspartic_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    calcium_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    carbohydrate_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    cholesterol_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    copper_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    cystine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    energy_kcal = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    energy_kj = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    fiber_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    glutamic_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    glycine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    histidine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    humidity_percents = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    iron_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    isoleucine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    leucine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    lipidius_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    lysine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    magnesium_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    manganes_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    methionine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    monounsaturated_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    niacin_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    phenylalanine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    phosphorus_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    polyunsaturated_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    potassium_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    proline_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    protein_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    pyridoxine_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    rae_mcg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    re_mcg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    retinol_mcg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    riboflavin_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    saturated_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    serine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    sodium_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    threonine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    tiamina_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    tryptophan_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    tyrosine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    valine_g = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    vitaminc_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)
    zinc_mg = models.DecimalField(blank=True, null=True,max_digits=8,decimal_places=2)

    class Meta:
        db_table = 'nutriente'
